# Generated by Django 5.0.6 on 2025-02-27 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_department_alter_profile_guardian_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='guardian_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
