# Generated by Django 5.0.6 on 2025-02-27 07:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('faculty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'conmplaint',
                'verbose_name_plural': 'conmplaints',
                'db_table': 'student_conmplaint',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Slot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slot_number', models.IntegerField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
            options={
                'verbose_name': 'slote',
                'verbose_name_plural': 'slotes',
                'db_table': 'student_slote',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'student',
                'verbose_name_plural': 'students',
                'db_table': 'users_student',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='FoodSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal', models.CharField(blank=True, choices=[('breakfast', 'Breakfast'), ('lunch', 'Lunch'), ('evening_snacks', 'Evening Snacks'), ('dinner', 'Dinner')], max_length=15, null=True)),
                ('selected', models.BooleanField(default=False)),
                ('day', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faculty.day')),
            ],
            options={
                'verbose_name': 'food_selection',
                'verbose_name_plural': 'food_selections',
                'db_table': 'student_food_selection',
                'ordering': ['id'],
            },
        ),
    ]
