# Generated by Django 5.0.6 on 2025-02-10 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_remove_complaint_title_alter_slot_booked_student'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slot',
            options={'ordering': ['id'], 'verbose_name': 'slote', 'verbose_name_plural': 'slotes'},
        ),
    ]
